const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = { token: sessionStorage.getItem('xy_admin_token') || '', role: sessionStorage.getItem('xy_admin_role') || '', licenses: [], devices: [], admins: [] };
const titles = {overview:'系统概览',licenses:'授权码管理',devices:'设备绑定',admins:'子管理员',releases:'版本控制'};

function toast(message, error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');el.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.hidden=true,3500)}
function fmt(value){return value?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'}
function short(value,n=16){return value?.length>n?value.slice(0,n)+'…':value||'—'}
function expiryLabel(row){if(row.expiry_type==='permanent')return '永久';if(row.expiry_type==='days')return `${row.duration_value} 天`;return `${row.duration_value} 个自然月`}
async function api(path, options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const res=await fetch(path,{...options,headers});if(res.status===204)return null;let data=null;try{data=await res.json()}catch{}if(!res.ok){if(res.status===401&&state.token)logout();const detail=typeof data?.detail==='string'?data.detail:JSON.stringify(data?.detail||data||{});throw new Error(detail||`请求失败 (${res.status})`)}return data}

async function checkHealth(){try{await api('/health/ready');$('#serverStatus').className='server-status ok';$('#serverStatus').innerHTML='<span></span>授权服务运行正常';$('#metricHealth').textContent='正常'}catch{$('#serverStatus').className='server-status bad';$('#serverStatus').innerHTML='<span></span>服务暂不可用';$('#metricHealth').textContent='异常'}}
function showApp(){if(!state.token)return;$('#loginView').hidden=true;$('#appView').hidden=false;$('#roleBadge').textContent=state.role==='owner'?'所有者':'子管理员';const owner=state.role==='owner';$('#adminsNav').hidden=!owner;$('#releasesNav').hidden=!owner;$('#assignedWrap').hidden=!owner;loadAll()}
function logout(){state.token='';state.role='';sessionStorage.removeItem('xy_admin_token');sessionStorage.removeItem('xy_admin_role');$('#appView').hidden=true;$('#loginView').hidden=false}

async function loadAll(){try{const jobs=[api('/admin/v1/licenses'),api('/admin/v1/activations')];if(state.role==='owner')jobs.push(api('/admin/v1/admins'));const values=await Promise.all(jobs);state.licenses=values[0];state.devices=values[1];state.admins=values[2]||[];render();await loadRelease()}catch(e){toast(e.message,true)}}
function render(){
  $('#metricLicenses').textContent=state.licenses.length;$('#metricActive').textContent=state.licenses.filter(x=>x.status==='active'&&(!x.expires_at||new Date(x.expires_at)>new Date())).length;$('#metricDevices').textContent=state.devices.filter(x=>x.status==='active').length;
  $('#licenseCount').textContent=state.licenses.length;$('#deviceCount').textContent=state.devices.length;$('#adminCount').textContent=state.admins.length;
  $('#licenseRows').replaceChildren(...(state.licenses.length?state.licenses.map(row=>{const tr=document.createElement('tr');tr.innerHTML=`<td><code>${row.masked_code}</code></td><td>${expiryLabel(row)}</td><td><span class="status ${row.status}">${row.status}</span></td><td>${fmt(row.expires_at)}</td><td title="${escapeHtml(row.note)}">${escapeHtml(short(row.note,20))}</td><td></td>`;if(row.status==='active'){const b=document.createElement('button');b.className='danger-button';b.textContent='吊销';b.onclick=()=>revokeLicense(row.id);tr.lastElementChild.append(b)}return tr}):[emptyRow(6,'暂无授权码')]))
  $('#deviceRows').replaceChildren(...(state.devices.length?state.devices.map(row=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${escapeHtml(row.device_name||'未命名设备')}</td><td><code title="${escapeHtml(row.device_id)}">${escapeHtml(short(row.device_id))}</code></td><td>${escapeHtml(row.app_version)}</td><td><span class="status ${row.status}">${row.status}</span></td><td>${fmt(row.last_seen_at)}</td><td></td>`;if(row.status==='active'){const b=document.createElement('button');b.className='danger-button';b.textContent='吊销设备';b.onclick=()=>revokeDevice(row.id);tr.lastElementChild.append(b)}return tr}):[emptyRow(6,'暂无设备绑定')]))
  $('#adminRows').replaceChildren(...(state.admins.length?state.admins.map(row=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${escapeHtml(row.username)}</td><td>${row.active_license_limit}</td><td><span class="status ${row.enabled?'':'revoked'}">${row.enabled?'启用':'禁用'}</span></td><td>${fmt(row.created_at)}</td>`;return tr}):[emptyRow(4,'暂无子管理员')]))
  const select=$('#assignedAdmin');select.replaceChildren(new Option('所有者本人',''),...state.admins.filter(x=>x.enabled).map(x=>new Option(`${x.username}（额度 ${x.active_license_limit}）`,x.id)));
}
function emptyRow(cols,text){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=cols;td.className='empty';td.textContent=text;tr.append(td);return tr}
function escapeHtml(value=''){return value.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function revokeLicense(id){if(!confirm('确定要远程吊销此授权码吗？客户端将在下次联网校验时停止使用。'))return;try{await api(`/admin/v1/licenses/${id}/revoke`,{method:'POST'});toast('授权码已吊销');await loadAll()}catch(e){toast(e.message,true)}}
async function revokeDevice(id){if(!confirm('确定吊销这台设备吗？'))return;try{await api(`/admin/v1/activations/${id}/revoke`,{method:'POST'});toast('设备授权已吊销');await loadAll()}catch(e){toast(e.message,true)}}
async function loadRelease(){try{const data=await api('/v1/releases/latest?channel=stable');if(!data)return;const r=data.release;$('#releaseCurrent').innerHTML=`<p><b>${escapeHtml(r.version)}</b> · ${r.channel}</p><p class="muted">${escapeHtml(r.notes||'无更新说明')}</p><p>最低版本：${r.minimum?'是':'否'}　强制更新：${r.mandatory?'是':'否'}　已禁止：${r.blocked?'是':'否'}</p>`}catch{}}

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));const data=await api('/admin/v1/session',{method:'POST',body:JSON.stringify(body)});state.token=data.access_token;state.role=data.role;sessionStorage.setItem('xy_admin_token',state.token);sessionStorage.setItem('xy_admin_role',state.role);e.target.reset();showApp();toast('登录成功')}catch(err){toast(err.message,true)}finally{button.disabled=false}})
$('#licenseForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const type=fd.get('expiry_type');const body={expiry_type:type,note:fd.get('note')||'',entitlements:{}};if(type!=='permanent')body.duration_value=Number(fd.get('duration_value'));if(fd.get('max_accounts'))body.max_accounts=Number(fd.get('max_accounts'));if(fd.get('assigned_admin_id'))body.assigned_admin_id=fd.get('assigned_admin_id');const button=e.submitter;button.disabled=true;try{const data=await api('/admin/v1/licenses',{method:'POST',body:JSON.stringify(body)});$('#newCode').textContent=data.license_code;$('#codeDialog').showModal();e.target.reset();$('#durationWrap').hidden=true;await loadAll()}catch(err){toast(err.message,true)}finally{button.disabled=false}})
$('#adminForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const body={username:fd.get('username'),password:fd.get('password'),active_license_limit:Number(fd.get('active_license_limit'))};try{await api('/admin/v1/admins',{method:'POST',body:JSON.stringify(body)});e.target.reset();toast('子管理员已创建');await loadAll()}catch(err){toast(err.message,true)}})
$('#releaseForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const body={version:fd.get('version'),channel:fd.get('channel'),download_url:fd.get('download_url'),sha256:fd.get('sha256'),notes:fd.get('notes')||'',signature:'',minimum:fd.has('minimum'),mandatory:fd.has('mandatory'),blocked:fd.has('blocked'),published:true};try{await api('/admin/v1/releases',{method:'POST',body:JSON.stringify(body)});e.target.reset();toast('版本策略已发布');await loadRelease()}catch(err){toast(err.message,true)}})
$('#expiryType').addEventListener('change',e=>{$('#durationWrap').hidden=e.target.value==='permanent'});$('#logoutBtn').onclick=logout;$('#refreshBtn').onclick=loadAll;$('#closeDialog').onclick=()=>$('#codeDialog').close();$('#copyCode').onclick=async()=>{await navigator.clipboard.writeText($('#newCode').textContent);toast('授权码已复制')};
$$('nav button').forEach(button=>button.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');$$('.panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===button.dataset.tab));$('#pageTitle').textContent=titles[button.dataset.tab]});
checkHealth();showApp();
